# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Analytica
tagline:          'Thoughts on Data, Computing, and Our World'
description:      'A blog for data, computing, and the myriad ways we can use them together to understand our world better.'

url:              http://nicholas-miklaucic.github.io
baseurl:          /

author:
  name:           'Nicholas Miklaucic'
  url:            https://github.com/nicholas-miklaucic

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicholas-miklaucic/analytica

gems:
  - jekyll-paginate
  - jekyll-gist
  - github-pages
  - jekyll-sitemap
