# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Analytica
tagline:          'Thoughts on Data, Computers, and Our World'
description:      'A blog about data, computing, and using those things to better understand our world.'

url:              https://nicholas-miklaucic.github.io
baseurl:          /

author:
  name:           'Nicholas Miklaucic'
  url:            https://github.com/nicholas-miklaucic

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicholas-miklaucic/analytica

gems:
  - jekyll-paginate
  - jekyll-gist
  - github-pages
  - jekyll-sitemap
  - kramdown
